import { tripLocationCatalog } from "@/features/trips/location-catalog";
import type { MockPlace, PlanningTopic } from "./types";

const cityCoordinates: Record<string, { latitude: number; longitude: number }> = {
  Amsterdam: { latitude: 52.3676, longitude: 4.9041 },
  Bangkok: { latitude: 13.7563, longitude: 100.5018 },
  Barcelona: { latitude: 41.3874, longitude: 2.1686 },
  Berlin: { latitude: 52.52, longitude: 13.405 },
  Bogota: { latitude: 4.711, longitude: -74.0721 },
  "Buenos Aires": { latitude: -34.6037, longitude: -58.3816 },
  Lisbon: { latitude: 38.7223, longitude: -9.1393 },
  London: { latitude: 51.5072, longitude: -0.1276 },
  "Los Angeles": { latitude: 34.0522, longitude: -118.2437 },
  Madrid: { latitude: 40.4168, longitude: -3.7038 },
  "Mexico City": { latitude: 19.4326, longitude: -99.1332 },
  Miami: { latitude: 25.7617, longitude: -80.1918 },
  "New York": { latitude: 40.7128, longitude: -74.006 },
  Paris: { latitude: 48.8566, longitude: 2.3522 },
  Prague: { latitude: 50.0755, longitude: 14.4378 },
  Rome: { latitude: 41.9028, longitude: 12.4964 },
  Seoul: { latitude: 37.5665, longitude: 126.978 },
  Sydney: { latitude: -33.8688, longitude: 151.2093 },
  Tokyo: { latitude: 35.6762, longitude: 139.6503 },
  Vienna: { latitude: 48.2082, longitude: 16.3738 },
};

type Template = Omit<
  MockPlace,
  | "id"
  | "city"
  | "country"
  | "latitude"
  | "longitude"
  | "address"
  | "estimatedCostCurrency"
>;

const templatesByTopic: Record<PlanningTopic, Template[]> = {
  HOTEL_BASE: [
    {
      name: "Gallery Quarter Hotel",
      category: "HOTEL",
      topic: "HOTEL_BASE",
      tags: ["MUSEUMS", "ART", "FOOD"],
      budgetLevels: ["MODERATE"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING", "PUBLIC_TRANSIT"],
      accommodationTypes: ["HOTEL"],
      customMatches: ["Quiet hotels", "Local markets"],
      description: "A calm hotel base near museums, cafes, and local markets.",
      rating: 4.7,
      priceLevel: 3,
      estimatedCostAmount: 210,
    },
    {
      name: "Central Transit Hotel",
      category: "HOTEL",
      topic: "HOTEL_BASE",
      tags: ["LOCAL_CULTURE", "ARCHITECTURE"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["BALANCED", "PACKED"],
      transportationModes: ["PUBLIC_TRANSIT", "MIXED"],
      accommodationTypes: ["HOTEL"],
      customMatches: ["Flexible afternoons"],
      description: "A practical central stay with easy transit connections.",
      rating: 4.3,
      priceLevel: 2,
      estimatedCostAmount: 145,
    },
    {
      name: "Design Stay",
      category: "HOTEL",
      topic: "HOTEL_BASE",
      tags: ["ART", "ARCHITECTURE", "PHOTOGRAPHY"],
      budgetLevels: ["MODERATE", "LUXURY"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING", "RIDE_SHARE"],
      accommodationTypes: ["HOTEL", "AIRBNB"],
      customMatches: ["Rooftop views", "Quiet mornings"],
      description: "A design-focused stay with photogenic common spaces.",
      rating: 4.6,
      priceLevel: 4,
      estimatedCostAmount: 260,
    },
    {
      name: "Family Comfort Base",
      category: "HOTEL",
      topic: "HOTEL_BASE",
      tags: ["LOCAL_CULTURE", "SHOPPING"],
      budgetLevels: ["MODERATE"],
      pace: ["RELAXED"],
      transportationModes: ["MIXED", "RIDE_SHARE"],
      accommodationTypes: ["HOTEL", "RESORT"],
      customMatches: ["Kid-friendly stops", "Quiet hotels"],
      description: "A quieter base with family-friendly access to main areas.",
      rating: 4.4,
      priceLevel: 3,
      estimatedCostAmount: 195,
    },
    {
      name: "Premium View Hotel",
      category: "HOTEL",
      topic: "HOTEL_BASE",
      tags: ["PHOTOGRAPHY", "WELLNESS"],
      budgetLevels: ["LUXURY"],
      pace: ["RELAXED"],
      transportationModes: ["RIDE_SHARE", "MIXED"],
      accommodationTypes: ["HOTEL", "RESORT"],
      customMatches: ["Rooftop views", "Late checkout"],
      description: "A polished high-comfort stay with strong views and amenities.",
      rating: 4.9,
      priceLevel: 5,
      estimatedCostAmount: 390,
    },
  ],
  ACTIVITIES: [
    {
      name: "Old Town Culture Walk",
      category: "ATTRACTION",
      topic: "ACTIVITIES",
      tags: ["HISTORY", "LOCAL_CULTURE", "ARCHITECTURE", "PHOTOGRAPHY"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING"],
      accommodationTypes: [],
      customMatches: ["Scenic walks", "Low-crowd attractions"],
      description: "A walkable route through historic streets and local corners.",
      rating: 4.6,
      priceLevel: 1,
      estimatedCostAmount: 25,
    },
    {
      name: "Signature Museum Visit",
      category: "ATTRACTION",
      topic: "ACTIVITIES",
      tags: ["MUSEUMS", "ART", "HISTORY"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING", "PUBLIC_TRANSIT"],
      accommodationTypes: [],
      customMatches: ["Quiet mornings"],
      description: "A museum stop that fits culture-heavy trip plans.",
      rating: 4.8,
      priceLevel: 2,
      estimatedCostAmount: 35,
    },
    {
      name: "Neighborhood Market Morning",
      category: "ACTIVITY",
      topic: "ACTIVITIES",
      tags: ["FOOD", "LOCAL_CULTURE", "SHOPPING"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["RELAXED"],
      transportationModes: ["WALKING"],
      accommodationTypes: [],
      customMatches: ["Local markets", "Independent cafes"],
      description: "A low-pressure morning built around market browsing.",
      rating: 4.5,
      priceLevel: 1,
      estimatedCostAmount: 30,
    },
    {
      name: "Urban Nature Break",
      category: "ACTIVITY",
      topic: "ACTIVITIES",
      tags: ["NATURE", "WELLNESS", "PHOTOGRAPHY"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING", "PUBLIC_TRANSIT"],
      accommodationTypes: [],
      customMatches: ["Flexible afternoons", "Scenic walks"],
      description: "A restorative outdoor stop between busier attractions.",
      rating: 4.4,
      priceLevel: 1,
      estimatedCostAmount: 15,
    },
    {
      name: "Hidden Gems Route",
      category: "LANDMARK",
      topic: "ACTIVITIES",
      tags: ["HIDDEN_GEMS", "LOCAL_CULTURE", "PHOTOGRAPHY"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["BALANCED", "PACKED"],
      transportationModes: ["WALKING", "MIXED"],
      accommodationTypes: [],
      customMatches: ["Low-crowd attractions", "Scenic walks"],
      description: "A cluster of lesser-known stops away from peak crowds.",
      rating: 4.3,
      priceLevel: 1,
      estimatedCostAmount: 20,
    },
  ],
  FOOD_NIGHTLIFE: [
    {
      name: "Independent Cafe Crawl",
      category: "RESTAURANT",
      topic: "FOOD_NIGHTLIFE",
      tags: ["FOOD", "LOCAL_CULTURE"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING"],
      accommodationTypes: [],
      customMatches: ["Independent cafes", "Quiet mornings"],
      description: "A set of relaxed cafes with a local feel.",
      rating: 4.6,
      priceLevel: 2,
      estimatedCostAmount: 28,
    },
    {
      name: "Local Dinner Room",
      category: "RESTAURANT",
      topic: "FOOD_NIGHTLIFE",
      tags: ["FOOD", "LOCAL_CULTURE"],
      budgetLevels: ["MODERATE"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING", "RIDE_SHARE"],
      accommodationTypes: [],
      customMatches: ["Local markets"],
      description: "A dinner option built around regional ingredients.",
      rating: 4.7,
      priceLevel: 3,
      estimatedCostAmount: 65,
    },
    {
      name: "Rooftop Evening Spot",
      category: "ENTERTAINMENT",
      topic: "FOOD_NIGHTLIFE",
      tags: ["NIGHTLIFE", "PHOTOGRAPHY", "MUSIC"],
      budgetLevels: ["MODERATE", "LUXURY"],
      pace: ["BALANCED", "PACKED"],
      transportationModes: ["RIDE_SHARE", "MIXED"],
      accommodationTypes: [],
      customMatches: ["Rooftop views"],
      description: "An evening stop with skyline views and music.",
      rating: 4.5,
      priceLevel: 4,
      estimatedCostAmount: 85,
    },
    {
      name: "Quiet Wine Bar",
      category: "RESTAURANT",
      topic: "FOOD_NIGHTLIFE",
      tags: ["FOOD", "NIGHTLIFE"],
      budgetLevels: ["MODERATE", "LUXURY"],
      pace: ["RELAXED"],
      transportationModes: ["WALKING", "RIDE_SHARE"],
      accommodationTypes: [],
      customMatches: ["Quiet mornings", "Quiet hotels"],
      description: "A slower evening option for conversation and small plates.",
      rating: 4.4,
      priceLevel: 3,
      estimatedCostAmount: 75,
    },
    {
      name: "Market Food Hall",
      category: "RESTAURANT",
      topic: "FOOD_NIGHTLIFE",
      tags: ["FOOD", "SHOPPING", "LOCAL_CULTURE"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["BALANCED", "PACKED"],
      transportationModes: ["WALKING", "PUBLIC_TRANSIT"],
      accommodationTypes: [],
      customMatches: ["Local markets", "Flexible afternoons"],
      description: "A flexible food stop with many quick local options.",
      rating: 4.3,
      priceLevel: 2,
      estimatedCostAmount: 35,
    },
  ],
  BUDGET_PACE: [
    {
      name: "Low-Cost Culture Loop",
      category: "ACTIVITY",
      topic: "BUDGET_PACE",
      tags: ["HISTORY", "LOCAL_CULTURE", "ARCHITECTURE"],
      budgetLevels: ["BUDGET"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["WALKING"],
      accommodationTypes: [],
      customMatches: ["Scenic walks"],
      description: "A cost-conscious route with several free or low-cost stops.",
      rating: 4.4,
      priceLevel: 1,
      estimatedCostAmount: 12,
    },
    {
      name: "Balanced Highlights Pass",
      category: "ACTIVITY",
      topic: "BUDGET_PACE",
      tags: ["MUSEUMS", "HISTORY", "ART"],
      budgetLevels: ["MODERATE"],
      pace: ["BALANCED"],
      transportationModes: ["PUBLIC_TRANSIT", "MIXED"],
      accommodationTypes: [],
      customMatches: ["Flexible afternoons"],
      description: "A balanced day plan that mixes paid and free highlights.",
      rating: 4.5,
      priceLevel: 2,
      estimatedCostAmount: 55,
    },
    {
      name: "Packed First-Timer Route",
      category: "LANDMARK",
      topic: "BUDGET_PACE",
      tags: ["ARCHITECTURE", "PHOTOGRAPHY", "LOCAL_CULTURE"],
      budgetLevels: ["MODERATE"],
      pace: ["PACKED"],
      transportationModes: ["MIXED", "PUBLIC_TRANSIT"],
      accommodationTypes: [],
      customMatches: ["Rooftop views"],
      description: "A higher-energy route for covering major areas efficiently.",
      rating: 4.6,
      priceLevel: 2,
      estimatedCostAmount: 60,
    },
    {
      name: "Slow Wellness Afternoon",
      category: "ACTIVITY",
      topic: "BUDGET_PACE",
      tags: ["WELLNESS", "NATURE"],
      budgetLevels: ["BUDGET", "MODERATE"],
      pace: ["RELAXED"],
      transportationModes: ["WALKING", "RIDE_SHARE"],
      accommodationTypes: [],
      customMatches: ["Flexible afternoons", "Quiet mornings"],
      description: "A slower block that protects recovery time in the plan.",
      rating: 4.2,
      priceLevel: 2,
      estimatedCostAmount: 45,
    },
    {
      name: "Premium Convenience Pick",
      category: "ACTIVITY",
      topic: "BUDGET_PACE",
      tags: ["LOCAL_CULTURE", "FOOD"],
      budgetLevels: ["LUXURY"],
      pace: ["RELAXED", "BALANCED"],
      transportationModes: ["RIDE_SHARE", "MIXED"],
      accommodationTypes: [],
      customMatches: ["Late checkout"],
      description: "A convenience-first option that trades cost for comfort.",
      rating: 4.7,
      priceLevel: 5,
      estimatedCostAmount: 140,
    },
  ],
};

function slug(value: string) {
  return value.toLocaleLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function currencyForCountry(country: string) {
  return country === "United States" ? "USD" : "EUR";
}

function withCity(template: Template, city: string, country: string, index: number) {
  const coordinates = cityCoordinates[city] ?? { latitude: 0, longitude: 0 };

  return {
    ...template,
    id: `${slug(city)}-${slug(template.topic)}-${index + 1}`,
    name: `${city} ${template.name}`,
    city,
    country,
    address: `${city} planning district`,
    latitude: Number((coordinates.latitude + index * 0.003).toFixed(7)),
    longitude: Number((coordinates.longitude + index * 0.003).toFixed(7)),
    estimatedCostCurrency: currencyForCountry(country),
  } satisfies MockPlace;
}

export const mockPlaces = tripLocationCatalog.flatMap((location) =>
  Object.values(templatesByTopic).flatMap((templates) =>
    templates.map((template, index) =>
      withCity(template, location.city, location.country, index),
    ),
  ),
);

export function getMockPlacesForCityTopic(
  city: string,
  country: string,
  topic: PlanningTopic,
) {
  return mockPlaces.filter(
    (place) =>
      place.city === city && place.country === country && place.topic === topic,
  );
}
