import {
  scenarioCatalogSchema,
  type QaEnvironment,
  type Scenario,
} from "../contracts/schemas";

const localAndPreview: QaEnvironment[] = ["local", "preview"];

const entries = [
  {
    id: "AUTH-P0-PROTECTION",
    title: "Protected pages and APIs reject anonymous access",
    feature: "authentication",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: ["local", "preview", "production"],
    executionKind: "browser",
    destructive: false,
    fixtureProfile: "anonymous",
    owningAgent: "qa_security_concurrency",
    tags: ["auth", "401", "redirect", "direct-route"],
    expectedInvariants: [
      "Protected pages redirect an anonymous visitor to login.",
      "Protected APIs return 401 without disclosing trip data.",
      "Direct navigation cannot bypass authentication.",
    ],
  },
  {
    id: "AUTH-P0-OWNERSHIP",
    title: "Trip ownership is enforced across reads and mutations",
    feature: "authentication",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "owner-and-intruder",
    owningAgent: "qa_security_concurrency",
    tags: ["auth", "ownership", "404", "server-action"],
    expectedInvariants: [
      "A second user receives owner-scoped 404 responses for another user's trip.",
      "Route handlers and Server Actions apply identical ownership checks.",
      "Rejected access causes no writes.",
    ],
  },
  {
    id: "AUTH-P1-SESSION",
    title: "Login, session persistence, and logout behave consistently",
    feature: "authentication",
    documentedStage: "existing foundation",
    priority: "P1",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: false,
    fixtureProfile: "qa-owner",
    owningAgent: "qa_journeys",
    tags: ["auth", "session", "logout", "navigation"],
    expectedInvariants: [
      "A valid QA session reaches authenticated pages after navigation and reload.",
      "Logout invalidates the session and returns the user to an unauthenticated state.",
      "The preview release includes manual Google OAuth callback evidence.",
    ],
  },
  {
    id: "PROFILE-P0-DEFAULTS",
    title: "Profile travel defaults persist and prefill trips",
    feature: "profile",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-empty-profile",
    owningAgent: "qa_journeys",
    tags: ["profile", "preferences", "persistence", "defaults"],
    expectedInvariants: [
      "All supported profile preferences survive a reload.",
      "New trips can opt into profile defaults without changing the profile.",
      "Trip-local overrides do not leak to other trips.",
    ],
  },
  {
    id: "TRIP-P0-CRUD",
    title: "Owned trip lifecycle persists end to end",
    feature: "trip-crud",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-ephemeral",
    owningAgent: "qa_journeys",
    tags: ["trip", "create", "update", "archive", "delete", "reload"],
    expectedInvariants: [
      "Create, read, update, archive, and delete operate only on the owned trip.",
      "Saved state survives browser back, forward, and reload navigation.",
      "Deleted trips cannot be reopened from a stale direct URL.",
    ],
  },
  {
    id: "TRIP-P0-READINESS",
    title: "Draft and planning-ready states enforce complete trip details",
    feature: "trip-crud",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-ephemeral",
    owningAgent: "qa_constraints",
    tags: ["trip", "draft", "readiness", "dates", "budget"],
    expectedInvariants: [
      "A title-only trip remains a valid draft.",
      "Planning requires destinations, a valid date range, budget, currency, and travel style.",
      "Today and same-day ranges are handled explicitly while past or reversed dates fail validation.",
    ],
  },
  {
    id: "TRIP-P1-BOUNDARIES",
    title: "Trip input boundaries and catalog pairs are enforced",
    feature: "trip-crud",
    documentedStage: "existing foundation",
    priority: "P1",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-ephemeral",
    owningAgent: "qa_constraints",
    tags: ["trip", "boundary", "destinations", "budget", "currency"],
    expectedInvariants: [
      "One through twelve destinations are accepted and a thirteenth is rejected.",
      "Zero, negative, extremely large, USD, and EUR budget boundaries produce documented results.",
      "Partial departure data and unsupported city-country pairs fail without partial writes.",
    ],
  },
  {
    id: "PREF-P0-VALIDATION",
    title: "Every preference enum and numeric bound is validated",
    feature: "trip-preferences",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip",
    owningAgent: "qa_constraints",
    tags: ["preferences", "enum", "bounds", "walking", "hotel"],
    expectedInvariants: [
      "Every documented enum value round-trips and unknown values fail.",
      "Hotel priority and walking tolerance bounds, including 0.5-km increments, are enforced.",
      "Missing required choices fail atomically.",
    ],
  },
  {
    id: "PREF-P1-COMBINATIONS",
    title:
      "Custom and conflicting preference combinations remain deterministic",
    feature: "trip-preferences",
    documentedStage: "existing foundation",
    priority: "P1",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip",
    owningAgent: "qa_constraints",
    tags: [
      "preferences",
      "deduplication",
      "dietary",
      "accessibility",
      "override",
    ],
    expectedInvariants: [
      "Comma and newline input is trimmed and deduplicated case-insensitively.",
      "Dietary, accessibility, avoidance, and custom-interest combinations persist without loss.",
      "Trip preferences override profile defaults only for the current trip.",
    ],
  },
  {
    id: "LOG-P0-MODES",
    title: "Flexible and ticketed logistics produce stable city windows",
    feature: "logistics",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-multicity-trip",
    owningAgent: "qa_constraints",
    tags: ["logistics", "flexible", "ticketed", "segments", "slots"],
    expectedInvariants: [
      "Every supported transport mode works in flexible and ticketed flows.",
      "Ordered multi-segment trips derive correct city windows and travel blocks.",
      "Every full day exposes exactly 48 half-hour slots before constraints are applied.",
    ],
  },
  {
    id: "LOG-P1-TIME-EDGES",
    title: "Logistics rejects invalid time and date combinations",
    feature: "logistics",
    documentedStage: "existing foundation",
    priority: "P1",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-multicity-trip",
    owningAgent: "qa_constraints",
    tags: ["logistics", "same-day", "time", "boundary", "atomicity"],
    expectedInvariants: [
      "Equal, reversed, and malformed timestamps are rejected as documented.",
      "Segments outside trip dates and impossible ordering cause no partial writes.",
      "Same-day transfers reduce capacity without producing negative city windows.",
    ],
  },
  {
    id: "REC-P0-GENERATION",
    title: "Mock recommendation batches are relevant and deterministic",
    feature: "mock-recommendations",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip",
    owningAgent: "qa_journeys",
    tags: ["recommendations", "readiness", "batch", "scoring", "deduplication"],
    expectedInvariants: [
      "Recommendation generation is unavailable until the topic is ready.",
      "A batch contains five unique results where fixture data permits.",
      "Identical state produces deterministic ordering and scoring.",
    ],
  },
  {
    id: "REC-P0-FEEDBACK",
    title: "Recommendation decisions preserve itinerary state",
    feature: "planning-feedback",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-recommendation-trip",
    owningAgent: "qa_journeys",
    tags: ["recommendations", "select", "reject", "deselect", "reroll"],
    expectedInvariants: [
      "Select, reject, deselect, and reroll update only the intended suggestion.",
      "Structured rejection reasons and latest-batch references remain queryable.",
      "Rerolls and feedback never silently delete unrelated itinerary items.",
    ],
  },
  {
    id: "REC-P1-CUSTOM-HISTORY",
    title: "Custom places and feedback history avoid duplicates",
    feature: "planning-feedback",
    documentedStage: "existing foundation",
    priority: "P1",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-recommendation-trip",
    owningAgent: "qa_constraints",
    tags: ["recommendations", "custom-place", "history", "duplicate"],
    expectedInvariants: [
      "Custom already-decided places can be added once and selected normally.",
      "Repeated decisions do not create duplicate place or feedback records.",
      "Historical decisions remain associated with the correct batch and trip.",
    ],
  },
  {
    id: "ITIN-P0-BUILD",
    title: "Draft itinerary builds deterministically without data loss",
    feature: "itinerary-draft",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-selected-places",
    owningAgent: "qa_constraints",
    tags: ["itinerary", "inclusive-dates", "pace", "cost", "unscheduled"],
    expectedInvariants: [
      "Inclusive trip dates and pace capacity produce the documented day structure.",
      "Hotel ordering and cost totals are deterministic across rebuilds.",
      "Selections that cannot be placed remain explicitly unscheduled rather than disappearing.",
    ],
  },
  {
    id: "CONFLICT-P0-RULES",
    title: "All conflict rules remain deduplicated and auditable",
    feature: "conflicts",
    documentedStage: "existing foundation",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-conflicting-trip",
    owningAgent: "qa_constraints",
    tags: ["conflicts", "severity", "currency", "history", "deduplication"],
    expectedInvariants: [
      "Budget, schedule, location, restaurant-coverage, and logistics conflicts have correct severity.",
      "Cross-currency uncertainty is surfaced rather than silently converted.",
      "Repeated checks deduplicate active conflicts and preserve resolved or ignored history.",
    ],
  },
  {
    id: "REV-P0-IDEMPOTENCY",
    title: "Planning mutations are replay-safe and revision-guarded",
    feature: "planning-revision-contracts",
    documentedStage: "Stage 0",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip",
    owningAgent: "qa_security_concurrency",
    tags: ["revision", "idempotency", "replay", "stale", "atomicity"],
    expectedInvariants: [
      "Replayed operation IDs return the prior result without duplicate writes.",
      "Concurrent duplicate operations commit at most once.",
      "A stale client revision is rejected before any state changes.",
    ],
    requiredEvidence: [
      "Exact commit, current migration head, database fingerprint, and fixture alias.",
      "Operation ID, mutation fingerprint, request ordering, expected/observed revisions, response status, and durable ledger/state delta.",
      "Sequential replay, bounded concurrent replay, stale revision, and operation-ID reuse with a different mutation fingerprint.",
    ],
  },
  {
    id: "REV-P0-CONCURRENCY",
    title: "Concurrent browser sessions converge safely",
    feature: "planning-revision-contracts",
    documentedStage: "Stage 0",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip-two-tabs",
    owningAgent: "qa_security_concurrency",
    tags: ["concurrency", "two-tab", "rapid-mutation", "conflict-refresh"],
    expectedInvariants: [
      "Two tabs editing one trip do not overwrite a newer accepted revision.",
      "Rapid selection changes preserve one internally consistent snapshot.",
      "Simultaneous conflict refreshes do not duplicate or lose conflict history.",
    ],
    requiredEvidence: [
      "Exact commit, current migration head, fixture alias, browser contexts, and action ordering.",
      "Pre/post planning revisions plus persisted state after both contexts reload.",
      "Bounded request timing and sanitized response/state artifacts.",
    ],
  },
  {
    id: "ADAPT-P0-VERSIONED-REPLACEMENT",
    title: "Item feedback creates an explainable copy-on-write replacement",
    feature: "adaptive-planning",
    documentedStage: "Adaptive planning vertical slice",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-selected-places",
    owningAgent: "qa_constraints",
    tags: [
      "candidate",
      "adaptation",
      "preferences",
      "copy-on-write",
      "conflicts",
    ],
    expectedInvariants: [
      "TOO_EXPENSIVE raises non-explicit price sensitivity and confidence by exactly 0.10 within bounds while explicit signals remain authoritative.",
      "The exact rejected suggestion is excluded and deterministic ranking uses score, rating, provider ID, then name.",
      "Only the affected item changes, unrelated days and accepted items are preserved, and a successor activates only after deterministic validation.",
      "No compatible replacement activates the preference version, preserves the active itinerary, and completes as NO_REPLACEMENT.",
    ],
    requiredEvidence: [
      "Captured trip, preference, and parent-itinerary versions plus the resulting preference delta.",
      "Before/after item identities for every day, deterministic candidate ordering, conflict summary, and active version pointers.",
      "A no-replacement execution proving that the parent itinerary remains active.",
    ],
  },
  {
    id: "ADAPT-P0-RELOAD-PROGRESS",
    title: "Adaptive progress and version history survive reload",
    feature: "adaptive-planning",
    documentedStage: "Adaptive planning vertical slice",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-selected-places",
    owningAgent: "qa_journeys",
    tags: [
      "candidate",
      "adaptation",
      "polling",
      "reload",
      "accessibility",
      "responsive",
    ],
    expectedInvariants: [
      "Item feedback controls are keyboard operable, clearly labelled, and expose pending state without hiding the current itinerary.",
      "Reload resumes polling from persisted active jobs and stops after a terminal state.",
      "The UI presents preference delta, explanation, affected day, retry guidance, provider provenance, and version history without exposing internal payloads.",
    ],
    requiredEvidence: [
      "Desktop and mobile browser evidence covering submission, reload during processing, terminal rendering, and keyboard operation.",
      "Sanitized feedback POST and bounded job GET response shapes correlated by job ID.",
    ],
  },
  {
    id: "JOB-P0-CLAIM-AND-STALE-SAFETY",
    title: "Concurrent workers claim once and stale attempts cannot activate",
    feature: "durable-planning-jobs",
    documentedStage: "Adaptive planning vertical slice",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip-two-tabs",
    owningAgent: "qa_security_concurrency",
    tags: [
      "candidate",
      "jobs",
      "skip-locked",
      "lease",
      "idempotency",
      "stale-write",
    ],
    expectedInvariants: [
      "Two atomic claimers cannot own one available job concurrently and duplicate delivery creates at most one successor version.",
      "An expired or reassigned attempt cannot persist provider results or activate preference or itinerary versions.",
      "A newer trip, preference, or parent-itinerary version causes the older job to finish SUPERSEDED without overwriting current state.",
      "Owner reads succeed while cross-user job and version reads remain non-disclosing.",
    ],
    requiredEvidence: [
      "Disposable PostgreSQL identity, claimant IDs, attempt numbers, lease timestamps, and claim ordering.",
      "Pre/post job, feedback, trip, and active-version rows for duplicate, reassigned, and superseded executions.",
    ],
  },
  {
    id: "JOB-P1-RECOVERY-AND-FAILURES",
    title:
      "Worker interruption, retries, and provider failures recover visibly",
    feature: "durable-planning-jobs",
    documentedStage: "Adaptive planning vertical slice",
    priority: "P1",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-provider-trip",
    owningAgent: "qa_resilience_production",
    tags: [
      "candidate",
      "worker",
      "heartbeat",
      "recovery",
      "retry",
      "dead-letter",
      "provider",
    ],
    expectedInvariants: [
      "Heartbeats renew a 30-second lease at five-second intervals and abandoned attempts recover without manual repair.",
      "Retry scheduling is bounded by the documented 5, 20, and 60 second policy and the third failed attempt dead-letters.",
      "SIGTERM stops new claims while current work completes or becomes safely recoverable.",
      "Provider timeout, quota, malformed response, and unavailable configuration preserve the active itinerary and expose sanitized guidance.",
    ],
    requiredEvidence: [
      "Structured worker logs, attempt/event timelines, retry availability timestamps, and recovery/dead-letter state.",
      "Evidence that logs and public DTOs omit database URLs, provider keys, raw payloads, and raw provider metadata.",
    ],
  },
  {
    id: "UI-P1-ACCESSIBILITY",
    title: "Critical current journeys are responsive and accessible",
    feature: "trip-crud",
    documentedStage: "existing foundation",
    priority: "P1",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-complete-trip",
    owningAgent: "qa_journeys",
    tags: ["ui", "mobile", "keyboard", "accessibility", "error-state"],
    expectedInvariants: [
      "Critical pages pass automated accessibility scans and keyboard navigation.",
      "Desktop and mobile layouts have accessible names and no horizontal overflow.",
      "Pending and error states remain actionable through back navigation and reload.",
    ],
  },
  {
    id: "CHAT-P0-PERSISTENCE",
    title: "Conversation order and optimistic reconciliation survive reload",
    feature: "conversation-persistence",
    documentedStage: "Stage 1A",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip",
    owningAgent: "qa_journeys",
    tags: ["planned", "conversation", "optimistic", "reload", "no-ai"],
    expectedInvariants: [
      "Persisted messages retain server order through optimistic reconciliation.",
      "Reload restores messages, preferences, selections, conflicts, and itinerary state.",
      "The deterministic chat shell remains usable with AI disabled.",
    ],
  },
  {
    id: "AI-P0-INTENT",
    title: "AI intent is validated and bounded before execution",
    feature: "ai-intent",
    documentedStage: "Stage 1B",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-conversation-trip",
    owningAgent: "qa_resilience_production",
    tags: ["planned", "ai", "schema", "ambiguous-reference", "fallback"],
    expectedInvariants: [
      "Malformed or out-of-scope model output cannot execute arbitrary mutations.",
      "Ambiguous references request clarification and corrections remain auditable.",
      "Token metadata and errors are recorded without raw prompts or secrets.",
    ],
  },
  {
    id: "SCHED-P0-SLOTS",
    title: "Live scheduling respects slots, meals, transfers, and limits",
    feature: "live-scheduling",
    documentedStage: "Stage 2A",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-dense-multicity-trip",
    owningAgent: "qa_constraints",
    tags: ["planned", "scheduler", "meal-window", "transfer", "unscheduled"],
    expectedInvariants: [
      "Activities and restaurants occupy deterministic thirty-minute slots within explicit limits.",
      "Meal windows and transfer-day capacity are respected.",
      "Unplaceable selections remain visible and create an actionable conflict.",
    ],
  },
  {
    id: "PLACES-P0-BOUNDARY",
    title: "Google Places is isolated behind a validated provider boundary",
    feature: "google-places",
    documentedStage: "Stage 2B",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-provider-trip",
    owningAgent: "qa_resilience_production",
    tags: ["candidate", "google", "normalization", "quota", "timeout"],
    expectedInvariants: [
      "Normalized provider results upsert by stable identity and retain provider labels.",
      "Empty, malformed, quota, and timeout responses produce recoverable states.",
      "Provider failures preserve prior selections and itinerary state and never expose server keys.",
    ],
  },
  {
    id: "PERF-P0-BUDGETS",
    title: "Planning interactions satisfy documented performance budgets",
    feature: "interaction-performance",
    documentedStage: "Stage 3A",
    priority: "P0",
    environments: ["preview"],
    executionKind: "agent",
    destructive: false,
    fixtureProfile: "stable-preview-baseline",
    owningAgent: "qa_resilience_production",
    tags: ["planned", "performance", "p95", "snapshot", "read-only"],
    expectedInvariants: [
      "Interaction, database-local, and initial-content p95 values meet stage budgets.",
      "Planning snapshots and query counts stay within documented limits.",
      "Read paths do not mutate data or broadly refresh the page.",
    ],
    requiredEvidence: [
      "Exact commit, migration head, stable fixture identity, preview environment, and provider mode.",
      "Cold samples excluded and at least 20 warm samples per claimed operation.",
      "Percentile method, p50/p95/max, query-count p95, payload-bytes p95, and separately reported provider latency.",
    ],
  },
  {
    id: "CACHE-P0-RESILIENCE",
    title: "Cache and rate limits do not become correctness dependencies",
    feature: "cache-rate-limits",
    documentedStage: "Stage 3B",
    priority: "P0",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: true,
    fixtureProfile: "qa-owner-ready-trip",
    owningAgent: "qa_resilience_production",
    tags: ["planned", "redis", "invalidation", "rate-limit", "fallback"],
    expectedInvariants: [
      "Cached and uncached requests are semantically equivalent and isolated per user and trip.",
      "Invalidation, timeout, and rate-limit paths are recoverable.",
      "The full deterministic flow works with AI, Google, and Redis disabled.",
    ],
  },
  {
    id: "PROD-P0-READONLY",
    title: "Production smoke verification cannot mutate application state",
    feature: "authentication",
    documentedStage: "Stage 3B",
    priority: "P0",
    environments: ["production"],
    executionKind: "browser",
    destructive: false,
    fixtureProfile: "preprovisioned-readonly-synthetic-user",
    owningAgent: "qa_resilience_production",
    tags: ["production", "read-only", "mutation-guard", "secrets"],
    expectedInvariants: [
      "Public, login, anonymous-protection, and preprovisioned read surfaces are healthy.",
      "Browser POST, PUT, PATCH, and DELETE requests are aborted by the QA harness.",
      "Smoke output contains no credentials, cookies, tokens, or provider secrets.",
    ],
  },
  {
    id: "MAP-P2-PRESENTATION",
    title:
      "Map markers and filters degrade safely when provider data is missing",
    feature: "maps",
    documentedStage: "post-prototype",
    priority: "P2",
    environments: localAndPreview,
    executionKind: "browser",
    destructive: false,
    fixtureProfile: "qa-owner-map-trip",
    owningAgent: "qa_journeys",
    tags: ["deferred", "map", "marker", "filter", "provider"],
    expectedInvariants: [
      "Markers and filters reflect authorized itinerary data.",
      "Missing coordinates or provider data does not break the itinerary.",
      "Private provider keys never reach rendered markup or logs.",
    ],
  },
  {
    id: "EXPORT-P2-INTEGRITY",
    title: "Authenticated PDF and JSON exports preserve trip integrity",
    feature: "export",
    documentedStage: "post-prototype",
    priority: "P2",
    environments: localAndPreview,
    executionKind: "integration",
    destructive: false,
    fixtureProfile: "qa-owner-large-special-character-trip",
    owningAgent: "qa_journeys",
    tags: ["deferred", "export", "pdf", "json", "authorization"],
    expectedInvariants: [
      "Only the owner can export and draft restrictions are explicit.",
      "Large trips and special characters produce valid PDF and JSON downloads.",
      "Export content matches the persisted itinerary without leaking internal data.",
    ],
  },
] satisfies Scenario[];

export const scenarioCatalog = Object.freeze(
  scenarioCatalogSchema.parse(entries),
);

export function validateScenarioCatalog(input: unknown) {
  return scenarioCatalogSchema.parse(input);
}
